normales:
  - albahaca1.jpg
  - arugula1.jpg
  - baby_leaves1.jpg
  - cebollino1.jpg
  - albahaca.jpg
  - perejil_italiano1.jpg
  - perejil_nacional1.jpg
hierbas_en_maceta:
  - albahaca.jpg
  - albahaca1.jpg
  - arugula1.jpg
  - baby_leaves1.jpg
  - cebollino1.jpg
  - perejil_italiano1.jpg
