normales:
  - title: Albahaca
    image: albahaca1.jpg
  - title: Arúgula
    image: arugula1.jpg
  - title: Baby Leaves
    image: baby_leaves1.jpg
  - title: Cebollino
    image: cebollino1.jpg
  - title: Perejil Italiano
    image: perejil_italiano1.jpg
  - title: Perejil Nacional
    image: perejil_nacional1.jpg

hierbas_en_maceta:
  - title: Albahaca
    image: albahaca.jpg
  - title: Romero
    image: romero.jpg
  - title: Hierbabuena
    image: hierbabuena.jpg
  - title: Orégano
    image: oregano.jpg
  - title: Tomillo
    image: tomillo.jpg
